twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Kafka
    - Elasticsearch
  welcome-message: Hello microservices!
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.joshua.twittertokafka: DEBUG
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){blue} %clr(%5p) %clr(---){faint} %clr(%-40.40logger{39}){blue} %clr(:){faint} %m%n%clr'
